---
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: opc
  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
    become: yes
    become_method: sudo
